### ISSUE TITLE
Ammo can be duplicated since the double click

### ISSUE THREAD

**Issue by Sina30** [VORPCORE/vorp_inventory-lua#130]
Ammo can be duplicated since the double click when you have 5 you can go down to 3 then it suddenly goes back up to 5

**Comment by Inepsa** [comment]
I tried to duplicate this and found something that could help track this down. Here's what i think is going on: Say I have max ammo set to 10 on incendiary shotgun ammo in ammo.lua for vorp weapons v2. Each box holds 4 rounds. I add two boxes to get to the set max of 8, then when I add another box it goes over the 8 max limit and doesn't take a box from the inventory.

I didn't notice on other ammo types because they can hold so much more ammo your hardly reach the max. I have updated inventory and core, no other issues or errors anywhere else

**Comment by outsider31000** [comment]
theres a config to choose double click or not update the script
