### ISSUE TITLE
Ammo dissapear

### ISSUE THREAD

**Issue by JustRoys** [VORPCORE/vorp_inventory-lua#202]
We have issues since the new update that certain ammo dissapear after they relog. for example they use express ammo and they can use and shoot it but after relogging its gone

**Comment by VarusXX** [comment]
It also dissapears after death and using E to respawn. We just prepares for Halloween and found this out. We are using the "UseClearAll=true" function and set all to false

**Comment by outsider31000** [comment]
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/87246847/8ac1486d-e971-4d05-b9c2-367d5bc3f855)
when i add ammo i had 54 i added 100 and it changes On the DB if the ammo is saving then there isnt an issue with the inventory  because using amo does not come from inventory, is from weapon scripts
after relog 
![image](https://github.com/VORPCORE/vorp_inventory-lua/assets/87246847/089ee5e0-c6bd-481c-80ad-aff51a5f699e)
I have the ammo

**Comment by outsider31000** [comment]
maybe try to update, becaus i just installd and everything works normaly
