### ISSUE TITLE
SCRIPT ERROR

### ISSUE THREAD

**Issue by RizzooTv** [VORPCORE/vorp_inventory-lua#4]
Since I have it on our live server, this error keeps appearing, I don't know what people are doing to trigger it, the status of the script is from this morning

[script:vorp_inventor] SCRIPT ERROR: @vorp_inventory/server/services/inventoryService.lua:432: table index is nil

**Comment by Sina30** [comment]
I get exactly the same error when I restart the server via txadmin

**Comment by outsider31000** [comment]
when did yall updated the script?

**Comment by outsider31000** [comment]
@Sina30  go to config file and set debug to false

**Comment by AndrewR3K** [comment]
I have not messed with this codebase at all yet, so could simply be the debug flag as @outsider31000  mentioned. 

But at initial glance, I wonder if it would help if lines 432-438 were put into the if statement starting I have not messed with this codebase yet, but at initial glance, it might help if lines 432-438 were put into the if statement starting on line 416. Because other wise you will be trying to pull a nil index from on line 432.

416: if sourceInventory ~= nil then

https://github.com/VORPCORE/vorp_inventory-lua/blob/d4722f4a4e6b6929cb906885d37f5700e87294fe/server/services/inventoryService.lua#L432

**Comment by outsider31000** [comment]
try the new version it's been updated.

**Comment by Sina30** [comment]
I no longer have any problems with the update and I have now set Debug to False
